### ISSUE TITLE
Erlang installation hangs

### ISSUE THREAD

**Issue by fkrause98** [HashNuke/asdf-erlang#264]
Hi!
First of all sorry if this issue is not to be posted here, close it if is the case.

Seems like the installation for OTP 22 and 23 hangs, the step  to reproduce it is simply running:
`asdf install erlang 22.3.4.19`.
Nothing gets logged, upon further inspection with this command: 
`tail -f ~/.asdf/plugins/erlang/kerl-home/builds/asdf_22.3.4.19/otp_build_22.3.4.19.log`, the first lines are:
```
patching file 'erts/configure.in'
Reversed (or previously applied) patch detected!  Assume -R? [y] 
*** It is not necessary to execute './otp_build autoconf' anymore! ***

```

Seems like it's waiting a confirmation of some sort, If I press "y" on the terminal running the asdf install command, the installation continues.

**Comment by Stratus3D** [comment]
@fkrause98 please provide the output of `asdf info`.

**Comment by fkrause98** [comment]
@Stratus3D 
Here it is:
```
OS:
Darwin franmac 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

SHELL:
fish, version 3.4.0

ASDF VERSION:
v0.10.0-77fd510

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/fran/.asdf

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master d08f506
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 0463971
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 65441d3


```

**Comment by Stratus3D** [comment]
You could try upgrading to the latest version of asdf-erlang (`asdf plugin-update erlang`) but I don't know that that will fix your issue.

**Comment by Stratus3D** [comment]
I am unable to replicate this issue on a newer version of the plugin. I'm on:

```
Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
```

**Comment by Stratus3D** [comment]
Any success @fkrause98 ?

**Comment by joecomscience** [comment]
I also have same issue 
```
OS:
Darwin joewalker-5.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

SHELL:
fish, version 3.5.1

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

```

**Comment by fkrause98** [comment]
> Any success @fkrause98 ?

Sorry for the late reply, yes, it still happens.

**Comment by Stratus3D** [comment]
@fkrause98 I merged https://github.com/asdf-vm/asdf-erlang/pull/263 a few hours ago. Did you update after I merged that?

**Comment by fkrause98** [comment]
Yes, I did.

But to be sure, I've just ran a plugin-update erlang and tried to install  22.3.4.19. It still happens.

**Comment by bklebe** [comment]
Confirming this happens with `23.3.4.14` and `23.3.4.18`. I'm running macOS Ventura `13.0.1 (22A400)`. The build succeeds if I press `y` and hit Enter.

**Comment by joecomscience** [comment]
step to reproduce the issue
1. go to dir `~/.asdf/plugins/erlang/kerl-home/builds/asdf_23.3.4`
2. run cmd `tail -f otp_build_23.3.4.log`
3. you'll see log
```
patching file 'erts/configure.in'
Reversed (or previously applied) patch detected!  Assume -R? [y]
```
4. press `y `and hit Enter.

**Comment by bryanenders** [comment]
I am seeing the same thing, regardless of the version of Erlang I attempt to install.

```
OS:
Darwin redacted.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

SHELL:
fish, version 3.6.0

ASDF VERSION:
v0.11.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master 1693b35
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 0d402e6
```
